### PR TITLE
feeder(adsbfi): Improve README

### PR DESCRIPTION
**Pull request by MaxWinterstein**
* Add `SERVICE_ENABLE_ADSBFI` to common section
* adjust naming to the style adsb.fi uses itself
* remove duplicated MLAT section

### CODE REVIEW

**Comment by Oli-BY** [comment]
what can i do to remove this error? I get it when i activate the Radarbox MLAT.

[radarbox-feeder] Traceback (most recent call last):
[radarbox-feeder]   File "/usr/local/share/radarbox-mlat-client/venv/bin/mlat-client", line 22, in <module>
[radarbox-feeder]     import mlat.client.version
[radarbox-feeder] ModuleNotFoundError: No module named 'mlat'

**Comment by Thom-x** [comment]
That's strange, because mlat is available, it's working on my side.
It might be due to the architecture. What are you running on  ?

**Comment by Oli-BY** [comment]
> That's strange, because mlat is available, it's working on my side.
> 
> It might be due to the architecture. What are you running on  ?



I use the addon for Home Assistant from Max Winterstein. Its on docker. I reinstalled today the addon but nothing changed. I still get the error message as long as Radarbox MLAT is activated. Radarbox ADS-B works well. Yes, i think something with my installation is wrong.

The last days Radarbox had problems with the server for the feeders. Support team told me that. Now is all fixed. 

FR24, dump1090, Piaware, adsbexchange, ADSBFI and Opensky are working perfectly

**Comment by Oli-BY** [comment]
Radarbox support team told me to do this and I have no idea what the impact would be. They always assume that everything runs on a Raspberry:

.....................................
Hi,
Please try the following MLAT install code

sudo apt purge mlat-client 
sudo apt update -y
sudo apt install -y git curl build-essential debhelper python-dev python3-dev 
cd
git clone https://github.com/mutability/mlat-client.git

cd mlat-client
sudo apt install -y dh-python
sudo dpkg-buildpackage -b -uc 

cd
sudo dpkg -i mlat-client_*.deb

........................................................

I can only use the terminal in Home Assistant. Sudo apt wont work i guess.

**Comment by MaxWinterstein** [comment]
Solved within https://github.com/Thom-x/docker-fr24feed-piaware-dump1090/issues/131

**Pull request merged**
