### PR TITLE
feat(feed): add radarbox support

### PR DESCRIPTION
**Pull request by Thom-x**

### CODE REVIEW

**Comment by Thom-x** [comment]
@deploy

**Comment by yousaf465** [comment]
@MaxWinterstein waiting for 1.27

**Comment by MaxWinterstein** [comment]
@yousaf465 released via https://github.com/MaxWinterstein/homeassistant-addons/pull/173

**Comment by Oli-BY** [comment]
I m sorry but i dont know where I can ask this. I dont get a feeder key for Radarbox. :-(
Can you help me please?

My log:
[radarbox-feeder] [2023-06-26 11:03:53]  ******** Statistics updated every 60 seconds ********
[radarbox-feeder] [2023-06-26 11:03:53]  Packets sent in the last 60 seconds: 1, Total packets sent since startup: 44
[radarbox-feeder] [2023-06-26 11:03:53]  Data sent: 924 B
[radarbox-feeder] [2023-06-26 11:03:53]  Data received: 1.2 KB
....
[radarbox-feeder] [2023-06-26 11:04:16]  Connection established.
[radarbox-feeder] [2023-06-26 11:04:16]  Empty sharing key. We will try to create a new one for you!
[radarbox-feeder] [2023-06-26 11:04:16]  CPU Serial empty. Use MAC address instead.
...
[radarbox-feeder] [2023-06-26 11:04:16]  Error creating new Sharing-Key: Could not create sharing-key

**Comment by LeonArmston** [comment]
Same here too sadly :(

**Comment by Oli-BY** [comment]
> where i can find this?
> 
> /etc/rbfeeder.ini
> 
> I have my problems to find this path.

I dont know why but i got the key now.
I added the configuration but now i got this message in the log:

[radarbox-feeder] Traceback (most recent call last):
[radarbox-feeder]   File "/usr/local/share/radarbox-mlat-client/venv/bin/mlat-client", line 22, in <module>
[radarbox-feeder]     import mlat.client.version
[radarbox-feeder] ModuleNotFoundError: No module named 'mlat'

**Comment by Oli-BY** [comment]
> Same here too sadly :(

Radarbox support helped me to get the key

**Comment by Oli-BY** [comment]
> > > Same here too sadly :(
> 
> > 
> 
> > Radarbox support helped me to get the key
> 
> 
> 
> any links?

Link for what?
Send them an e-mail.

support@radarbox.com

**Pull request merged**
