### PR TITLE
Build with PiAware and Dump1090 V8.2

### PR DESCRIPTION
**Pull request by zuhairmahd**
Thanks for your work on this.  This is a simple change to Dockerfile to make V8.2 the default build.
Thanks,
Zuhair.

### CODE REVIEW

**Comment by Thom-x** [comment]
Hi @zuhairmahd 
I just merged https://github.com/Thom-x/docker-fr24feed-piaware-dump1090/pull/112
It should have the new version on latest soon.

**Comment by zuhairmahd** [comment]
Great. Don't worry about today's commit -- that was made in error. :-).

**Comment by Thom-x** [comment]
It was a good reminder for me to reply to you 😁

**Comment by zuhairmahd** [comment]
Goes to show not all unintended consequences are bad. :-). :-).

**Comment by zuhairmahd** [comment]
I'll close this PR then @Thom-x

**Comment by zuhairmahd** [comment]
Handled in #112 so this is now moot.

**Pull request closed without merging**
