### PR TITLE
feat(radarbox): Implement rbfeeder_fixcputemp

### PR DESCRIPTION
**Pull request by FlyGoat**
Use LD_PRELOAD hook to workaround radarbox cpu temperature segfault issue. Allow container to run on userspace podman where sysfs volume is impossible.

### CODE REVIEW

**Comment by Thom-x** [comment]
@deploy

**Comment by Thom-x** [comment]
@FlyGoat thank you for the PR ! I let you test the image before merging ?

**Comment by FlyGoat** [comment]
@Thom-x Yes it works fine on my side, saving me from the sysfs hack.

**Comment by FlyGoat** [comment]
Ah sorry I think I misunderstood your comment.
Do you want me to test the image built from actions of your repo?

**Comment by FlyGoat** [comment]
@Thom-x Ah sorry for the problems on ghcr stuff, do you mind triggering deploy for this PR again?

**Comment by Thom-x** [comment]
@deploy

**Comment by FlyGoat** [comment]
Just tested on my system and it’s working as intended.
Thanks

**Pull request merged**
