### PR TITLE
Better UI integration with FlightRadar24 in addition to FlightAware - continued

### PR DESCRIPTION
**Pull request by e2jk**
Creating a second PR so that #45 can be merged while work continues on this one.
This PR will take care of adding links to the FR24 flight page.

### CODE REVIEW

**Comment by e2jk** [comment]
Trying to @deploy this PR (I guess only @Thom-x should be able to do so...)

**Comment by e2jk** [comment]
Hmmm, well, looks like the Github action did get triggered on my previous message.
I'm not sure @Thom-x if you think others should be able to deploy to the Docker hub just by having created a PR (OK, this doesn't push the `latest` tag, but technically it means somebody could publish malicious code to the Docker hub with a PR tag under your project's namespace???)

**Comment by Thom-x** [comment]
No, I have to approve the push to docker 😉.
Thanks for warning me anyway.

**Comment by e2jk** [comment]
Ok, makes sense, needing your approval is indeed the right setup.
Would you be able to upload this one to the Docker Hub, so that I can confirm on my live radar setup that the links work fine (I couldn't test with real planes coming over, as my dev machine doesn't have access to the feed coming from the antenna). Thanks.

**Comment by Thom-x** [comment]
https://hub.docker.com/layers/thomx/fr24feed-piaware/PR-49/images/sha256-8021fe070ffa870a289f0619f305b3942fae9812abbeb9aaeb66c979c0bfe5f6?context=repo

**Comment by Thom-x** [comment]
The preview of html files are here https://deploy-preview-49--docker-fr24feed-piaware-dump1090.netlify.app
Netlify is building it at every commit.

**Comment by e2jk** [comment]
Aaah, this is great, very helpful.
And now I notice the `deploy-preview` "check" linking directly to that page, very useful.
Just for my understanding: how did you get the "dummy" list of airplanes to work? That would be very helpful for me to get while developing these features? Is that dataset updated regularly (seems to be from yesterday, if I see the flights listed)

**Comment by Thom-x** [comment]
I added static files under `public_html/data/xxx.json`, I got this list from a public rtl sdr panel.
The dataset is not updated, I configured it on Netlify side.

**Comment by e2jk** [comment]
I noticed the link to the ICAO ID didn't always work for FR24, so I changed it to the Flight ID.
Could you push the PR tag to Docker Hub again please?

**Comment by Thom-x** [comment]
@deploy

**Review by Thom-x — APPROVED** [review]

**Comment by Thom-x** [comment]
@deploy

**Comment by e2jk** [comment]
Hi @Thom-x , could you please re- @Deploy ?
I have created a new environment variable `HTML_DEFAULT_TRACKER` to let the user define if they want the default link (shown in the table with the flight ID) to go to FlightAware (the default value) or to Flightradar24. I'm not yet that familiar with `confd` and the `getv` command, hopefully I plugged this in correctly?

**Comment by Thom-x** [comment]
@deploy

**Comment by e2jk** [comment]
Hi @Thom-x , the deploy doesn't seem to have pushed a new tag, as [tag PR-49](https://hub.docker.com/layers/thomx/fr24feed-piaware/PR-49/images/sha256-cf4cca8e35fc2c76b6766b23da6b0f973d6c75060fad0e4070c434cf44f45fd5?context=explore) still indicates "Last pushed3 days ago". Can you reforce that please?

**Comment by e2jk** [comment]
OK, `HTML_DEFAULT_TRACKER` works great, I've now added `HTML_RECEIVER_STATS_PAGE_FLIGHTAWARE` and `HTML_RECEIVER_STATS_PAGE_FLIGHTRADAR24` to allow specifying the ADS-B stats pages for the receiver on both FA and FR24 websites.
@Thom-x can you trigger a new @Deploy ?
This change is mostly done, only adding one more link for the local FR24 Feeder Status page (a.k.a. http://localhost:8754/) and this can be merged too...

**Comment by Thom-x** [comment]
@deploy

**Comment by Thom-x** [comment]
Great ! The link to fr24 feed status must be configurable also 👍

**Comment by e2jk** [comment]
There we go, this should be the last commit to this PR.
@Thom-x let's try a last @Deploy and if that's good, I'll let you confirm that this is good to merge (and close #44).

**Comment by Thom-x** [comment]
@deploy

**Comment by Thom-x** [comment]
I hope there will be not too much work to do when merging #48

**Comment by Thom-x** [comment]
You should add the new params in https://github.com/Thom-x/docker-fr24feed-piaware-dump1090/blob/master/docker-compose.yml

**Comment by e2jk** [comment]
Which of the 4 new parameters would you like in the `docker-compose.yml`, since they are all optional and depending on which feeders you have turned on (e.g. `HTML_FR24_FEEDER_STATUS_PAGE` doesn't make sense if you don't feed to FR24, or `HTML_RECEIVER_STATS_PAGE_FLIGHTAWARE` if you don't feed to FA?
Suggestion: I could add all 4 of the new parameters, commented out?

**Comment by e2jk** [comment]
> I hope there will be not too much work to do when merging #48

What I propose is:
- merge this #49 to the main branch
- release a new `latest` based on v3.8.1
- then work on adapting the patch to the v5 version

You'll have to tell me if you want the patch to apply to the `public_html_merged` or `public_html` or both (I do see you adapted already to the `public_html_merged` version, so we forget about the original page?)

**Comment by Thom-x** [comment]
Docker-compose like you did is fine.
We will merge this PR and work on v5, only with "merged" UI.

**Pull request merged**
