### PR TITLE
feat(feeder): refacto adsbfi support

### PR DESCRIPTION
**Pull request by Thom-x**

### CODE REVIEW

**Comment by Thom-x** [comment]
@deploy

**Comment by plo53** [comment]
Hi Thomas,

I am wondering how you deal with dump1090 dependency when both AdsbExchange and Adsbfi are enabled.

When I tried to implement a dedicated bundle for Adsbfi, then there was a clash starting dump1090 because the usb dev was already in use with the dump1090 instance of AdsbExhange.

Cordialement

**Comment by Thom-x** [comment]
They both have dependency on dump1090, but it is started only once, the dep folder means wait for it to be started before continuing.

**Comment by Thom-x** [comment]
@deploy

**Pull request merged**
