### PR TITLE
feat(feed): add adsbhub support

### PR DESCRIPTION
**Pull request by Thom-x**

### CODE REVIEW

**Comment by Thom-x** [comment]
@deploy

**Comment by Thom-x** [comment]
@deploy

**Comment by Thom-x** [comment]
@deploy

**Comment by Thom-x** [comment]
@deploy

**Comment by Thom-x** [comment]
@deploy

**Comment by Thom-x** [comment]
@deploy

**Comment by Thom-x** [comment]
@deploy

**Comment by LeonArmston** [comment]
Thanks - looking forward to adding adsbhub support!

Could you please advise which settings do I need to use when creating the station on adsbhub? Server, Data Protocol, Port etc?

image

**Comment by Thom-x** [comment]
Here is my config
image

**Pull request merged**
