### PR TITLE
add support for rpi4 and other architechtures

### PR DESCRIPTION
**Pull request by ms32035**
* For now no CI build of docker container
* conf.d has no arm32 binaries, so had to switch to building from sources

### CODE REVIEW

**Comment by Thom-x** [comment]
Thank you ! :bow: 
I'll test it a bit and merge.

**Comment by Thom-x** [comment]
We could add arm architecture for Travis.
https://blog.travis-ci.com/2019-10-07-multi-cpu-architecture-support

**Comment by ms32035** [comment]
> We could add arm architecture for Travis.
> https://blog.travis-ci.com/2019-10-07-multi-cpu-architecture-support

There's a bit more to that, specifically manifest + raspbian is mostly armhf (32 bit) as of now

**Comment by Thom-x** [comment]
Oh ok... Armhf is missing on Travis too bad.

**Comment by Thom-x** [comment]
We cannot update to the latest version, see #14.

**Comment by Thom-x** [comment]
I got an error running it with a locally built image (with the latest image it's working fine):

```
[cont-init.d] done.,
[services.d] starting services,
2020-07-01 10:04:33 | [main][i]FR24 Feeder/Decoder,
2020-07-01 10:04:33 | [main][i]Version: 1.0.18-5/generic,
2020-07-01 10:04:33 | [main][i]Built on Mar  4 2016 16:26:55 (devel-d11ca48.git/Linux/x86_64),
2020-07-01 10:04:33 | [main][i]Copyright 2012-2016 Flightradar24 AB,
2020-07-01 10:04:33 | [main][i]http://flightradar24.com,
Wed Jul  1 10:04:33 2020 UTC  dump1090-fa v3.8.1 starting up.,
2020-07-01 10:04:33 | [main][i]DNS mode: LIBC,
[services.d] done.,
2020-07-01 10:04:33 | [main][i]Automatic updates are DISABLED,
2020-07-01 10:04:33 | [main][i]Reader thread started,
2020-07-01 10:04:33 | [main][i]MLAT data feed started,
2020-07-01 10:04:33 | [master][i]Starting processing thread,
2020-07-01 10:04:33 | [httpd][i]Server started, listening on 0.0.0.0:8754,
2020-07-01 10:04:33 | [mlat][i]Waiting for MLAT configuration,
2020-07-01 10:04:33 | [reader][i]Initializing reader,
2020-07-01 10:04:33 | [reader][i]Connecting to Beast receiver via (tcp://127.0.0.1:30005),
2020-07-01 10:04:33 | [reader][e]Could not connect to tcp://127.0.0.1:30005,
rtlsdr: using device #0: Generic RTL2832U (Generic, RTL2832U, SN XXXXXXXXXXXXXXX),
****************************************************,
piaware version 3.8.1 is running, process ID 312,
your system info is: Linux 059829c81990 4.19.0-8-amd64 #1 SMP Debian 4.19.98-1+deb10u1 (2020-04-27) x86_64 GNU/Linux,
Found Rafael Micro R820T tuner,
rtlsdr: tuner gain set to 49.6 dB,
Allocating 4 zero-copy buffers,
2020-07-01 10:04:34 | [time][i]Synchronizing time via NTP,
Connecting to FlightAware adept server at piaware.flightaware.com/1200,
Connection with adept server at piaware.flightaware.com/1200 established,
TLS handshake with adept server at piaware.flightaware.com/1200 completed,
FlightAware server certificate validated,
encrypted session established with FlightAware,
adept reported location: 47.xxxx, -1.xxxx, 125ft AMSL,
Receiver location changed, restarting dump1090 and skyaware978,
attempting to restart dump1090.. ,
can't restart dump1090, no services that look like dump1090 found,
attempting to restart skyaware978.. ,
can't restart skyaware978, no services that look like skyaware978 found,
logged in to FlightAware as user xxxx,
my feeder ID is xxxxxxxxxxxxxxxxxxxxxxxxxxxx,
site statistics URL: https://flightaware.com/adsb/stats/user/xxxxxxxxxx,
multilateration data requested,
Starting multilateration client: /usr/lib/piaware/helpers/fa-mlat-client --input-connect 127.0.0.1:30005 --input-type auto --results beast,connect,localhost:30104 --results beast,listen,30105 --results ext_basestation,listen,30106 --udp-transport 70.42.6.225:18736:131756960,
mlat-client(349): fa-mlat-client 0.2.11 starting up,
mlat-client(349): Using UDP transport to 70.42.6.225 port 18736,
mlat-client(349): Listening for Beast-format results connection on port 30105,
mlat-client(349): Listening for Extended Basestation-format results connection on port 30106,
mlat-client(349): Route MTU changed to 1500,
mlat-client(349): Input connected to 127.0.0.1:30005,
2020-07-01 10:04:36 | [time][i]Time synchronized correctly, offset -0.0001 seconds,
2020-07-01 10:04:36 | [main][i]Feed Network client started,
2020-07-01 10:04:36 | [feed][i]Downloading configuration,
ADS-B data program 'dump1090' is listening on port 30005, so far so good,
Starting faup1090: /usr/lib/piaware/helpers/faup1090 --net-bo-ipaddr 127.0.0.1 --net-bo-port 30005 --stdout --lat xxxx --lon -xxxxxx,
Started faup1090 (pid 353) to connect to dump1090,
UAT support disabled by local configuration setting: uat-receiver-type,
2020-07-01 10:04:37 | [feed][c]Interval: 5s,
2020-07-01 10:04:37 | [feed][c]Latitude: xxxxxxx,
2020-07-01 10:04:37 | [feed][c]Longitude: -xxxxx,
2020-07-01 10:04:37 | [feed][c]GND: YES,
2020-07-01 10:04:37 | [feed][c]NonADSB: YES,
2020-07-01 10:04:37 | [feed][c]Timestamps: optional,
2020-07-01 10:04:37 | [feed][c]Max range AIR: 350.0nm,
2020-07-01 10:04:37 | [feed][c]Max range GND: 100.0nm,
2020-07-01 10:04:37 | [feed][i]defined 4 servers,
2020-07-01 10:04:37 | [feed][n]xxxxxxxxxxxxxxxxxxxxx,
2020-07-01 10:04:37 | [feed][n]connecting,
2020-07-01 10:04:37 | [stats][i]Stats thread started,
mlat-client(349): Disconnecting from 127.0.0.1:30005: Client shutting down,
mlat-client(349): Exiting on exception,
mlat-client(349): Traceback (most recent call last):,
mlat-client(349):   File "/tmp/piaware_builder/package-buster/debian/venv/lib/python3.7/site-packages/mlat/client/output.py", line 115, in reconnect,
mlat-client(349):     flags=0),
mlat-client(349):   File "/usr/lib/python3.7/socket.py", line 748, in getaddrinfo,
mlat-client(349):     for res in _socket.getaddrinfo(host, port, family, type, proto, flags):,
mlat-client(349): socket.gaierror: [Errno -2] Name or service not known,
mlat-client(349): During handling of the above exception, another exception occurred:,
mlat-client(349): Traceback (most recent call last):,
mlat-client(349):   File "/tmp/piaware_builder/package-buster/debian/venv/bin/fa-mlat-client", line 53, in <module>,
mlat-client(349):     main(),
mlat-client(349):   File "/tmp/piaware_builder/package-buster/debian/venv/bin/fa-mlat-client", line 48, in main,
mlat-client(349):     coordinator.run_until(lambda: adept.closed),
mlat-client(349):   File "/tmp/piaware_builder/package-buster/debian/venv/lib/python3.7/site-packages/mlat/client/coordinator.py", line 111, in run_until,
mlat-client(349):     self.heartbeat(now),
mlat-client(349):   File "/tmp/piaware_builder/package-buster/debian/venv/lib/python3.7/site-packages/mlat/client/coordinator.py", line 123, in heartbeat,
mlat-client(349):     o.heartbeat(now),
mlat-client(349):   File "/tmp/piaware_builder/package-buster/debian/venv/lib/python3.7/site-packages/mlat/client/output.py", line 138, in heartbeat,
mlat-client(349):     self.reconnect(),
mlat-client(349):   File "/tmp/piaware_builder/package-buster/debian/venv/lib/python3.7/site-packages/mlat/client/output.py", line 117, in reconnect,
mlat-client(349):     self.log('{ex!s}', ex=e),
mlat-client(349):   File "/tmp/piaware_builder/package-buster/debian/venv/lib/python3.7/site-packages/mlat/client/output.py", line 104, in log,
mlat-client(349):     what=self.describe(), host=self.addr[0], port=self.addr[1],,
mlat-client(349): AttributeError: 'OutputConnector' object has no attribute 'describe',
got EOF from multilateration client,
fa-mlat-client exited normally,
2020-07-01 10:04:37 | [feed][n]connected via UDP (fd 9),
2020-07-01 10:04:37 | [feed][n]working,
2020-07-01 10:04:38 | [reader][i]Connecting to Beast receiver via (tcp://127.0.0.1:30005),
2020-07-01 10:04:38 | [reader][i]Connected to the receiver, configuring,
2020-07-01 10:04:38 | [reader][i]Configured, processing messages,
```

**Comment by ms32035** [comment]
That doesn't seem to have anything to do with the changes I made. First is a dns failure, second is invalid handling of it in some python package, that probably was there and only surfaced. Could be cause by some issues in your docker networking, or something changed in the hundreds of packages that are updated on every build.

**Comment by Thom-x** [comment]
I'll try again with docker CI

Le mer. 1 juil. 2020 à 19:32, Marcin Szymański <notifications@github.com> a
écrit :

**Pull request merged**
